---
name: Spec
"on":
  push:
    branches:
      - trunk
concurrency:
  group: spec-state-${{ github.head_ref }}
env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
permissions: {}
jobs:
  spec-state:
    name: spec-state
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: artichoke
          persist-credentials: false

      - name: Install Rust toolchain
        uses: artichoke/setup-rust/build-and-test@68e0ebb3b406970de1cc2ca807797c9156a198a7 # v2.0.1
        with:
          toolchain: "1.88.0"

      - name: Compile spec-runner
        run: cargo build --release --verbose --bin spec-runner
        working-directory: "artichoke/spec-runner"

      - name: Set commit metadata
        id: commit
        run: |
          commit_date="$(git show --no-patch --format="%cs")"
          commit_year="$(git show --no-patch --date="format:%Y" --format="%cd")"
          commit_month="$(git show --no-patch --date="format:%m" --format="%cd")"
          commit_hash="$(git show --no-patch --format="%H")"

          echo "Commit date: ${commit_date}"
          echo "Commit year: ${commit_year}"
          echo "Commit month: ${commit_month}"
          echo "Commit hash: ${commit_hash}"

          echo "date=${commit_date}" >> $GITHUB_OUTPUT
          echo "year=${commit_year}" >> $GITHUB_OUTPUT
          echo "month=${commit_month}" >> $GITHUB_OUTPUT
          echo "hash=${commit_hash}" >> $GITHUB_OUTPUT
        working-directory: "artichoke"

      - name: Set spec tags artifact paths
        id: tagged
        run: |
          yaml="$(git show --no-patch --format="spec-tagged-%cs-rev-%H.yaml")"
          json="$(git show --no-patch --format="spec-tagged-%cs-rev-%H.json")"

          echo "Spec tags YAML: ${yaml}"
          echo "Spec tags JSON: ${json}"

          echo "yaml=${yaml}" >> $GITHUB_OUTPUT
          echo "json=${json}" >> $GITHUB_OUTPUT
        working-directory: "artichoke"

      - name: Set spec exceptions artifact paths
        id: exceptions
        run: |
          yaml="$(git show --no-patch --format="spec-exceptions-%cs-rev-%H.yaml")"
          json="$(git show --no-patch --format="spec-exceptions-%cs-rev-%H.json")"

          echo "Spec exceptions YAML: ${yaml}"
          echo "Spec exceptions JSON: ${json}"

          echo "yaml=${yaml}" >> $GITHUB_OUTPUT
          echo "json=${json}" >> $GITHUB_OUTPUT
        working-directory: "artichoke"

      - name: Generate spec tags
        run: |
          ./artichoke/spec-runner/target/release/spec-runner --quiet --format tagger artichoke/spec-runner/spec-state.toml | tee "${YAML_DEST}"
          ./artichoke/spec-runner/scripts/spec-yaml-to-json.rb "${YAML_DEST}" > "${JSON_DEST}"
        env:
          YAML_DEST: ${{ steps.tagged.outputs.yaml }}
          JSON_DEST: ${{ steps.tagged.outputs.json }}

      - name: Generate spec exceptions
        run: |
          ./artichoke/spec-runner/target/release/spec-runner --quiet --format yaml artichoke/spec-runner/spec-state.toml | tee "${YAML_DEST}"
          ./artichoke/spec-runner/scripts/spec-yaml-to-json.rb "${YAML_DEST}" > "${JSON_DEST}"
        env:
          YAML_DEST: ${{ steps.exceptions.outputs.yaml }}
          JSON_DEST: ${{ steps.exceptions.outputs.json }}

      - name: Checkout spec state repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: artichoke/spec-state
          path: spec-state
          ssh-key: ${{ secrets.SPEC_STATE_SSH_DEPLOY_PRIVATE_KEY }}
          persist-credentials: true

      - name: Copy spec-state reports
        run: |
          # tags
          mkdir -p "spec-state/reports/tagged/${OUTPUT_YEAR}/${OUTPUT_MONTH}"
          cp "${TAGGED_OUTPUT_JSON}" "spec-state/reports/tagged/${OUTPUT_YEAR}/${OUTPUT_MONTH}/${TAGGED_OUTPUT_JSON}"
          cp "${TAGGED_OUTPUT_JSON}" "spec-state/reports/tagged/${OUTPUT_YEAR}/${OUTPUT_MONTH}/latest.json"
          cp "${TAGGED_OUTPUT_JSON}" "spec-state/reports/tagged/${OUTPUT_YEAR}/latest.json"
          cp "${TAGGED_OUTPUT_JSON}" "spec-state/reports/tagged/latest.json"
          # exceptions
          mkdir -p "spec-state/reports/exceptions/${OUTPUT_YEAR}/${OUTPUT_MONTH}"
          cp "${EXCEPTIONS_OUTPUT_JSON}" "spec-state/reports/exceptions/${OUTPUT_YEAR}/${OUTPUT_MONTH}/${EXCEPTIONS_OUTPUT_JSON}"
          cp "${EXCEPTIONS_OUTPUT_JSON}" "spec-state/reports/exceptions/${OUTPUT_YEAR}/${OUTPUT_MONTH}/latest.json"
          cp "${EXCEPTIONS_OUTPUT_JSON}" "spec-state/reports/exceptions/${OUTPUT_YEAR}/latest.json"
          cp "${EXCEPTIONS_OUTPUT_JSON}" "spec-state/reports/exceptions/latest.json"
        env:
          TAGGED_OUTPUT_JSON: ${{ steps.tagged.outputs.json }}
          EXCEPTIONS_OUTPUT_JSON: ${{ steps.exceptions.outputs.json }}
          OUTPUT_YEAR: ${{ steps.commit.outputs.year }}
          OUTPUT_MONTH: ${{ steps.commit.outputs.month }}

      - name: Push spec-state
        run: |
          cat <<EOF > message.txt
          spec-state 💎📈

          As of artichoke/artichoke@${AS_OF_COMMIT}.

          Generated with the spec-state.yaml GitHub Actions workflow.
          EOF
          git add reports
          git -c user.name=artichoke-ci -c user.email=ci@artichokeruby.org commit --file=message.txt --allow-empty
          git push origin trunk
        working-directory: "spec-state"
        env:
          AS_OF_COMMIT: ${{ steps.commit.outputs.hash }}
